name: Run tests on dev branch

on:
  push:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test-environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start server and test with environment variables
        env:
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
          COOKIE_PASSWORD: ${{ secrets.COOKIE_PASSWORD }}
          DB: ${{ secrets.DB }}
          PORT: 4000
        run: npm run start_and_test
