name: Run tests on dev branch

on:
  push:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test-environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start server with environment variables
        env:
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
          COOKIE_PASSWORD: ${{ secrets.COOKIE_PASSWORD }}
          DB: ${{ secrets.DB }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
          CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
          PORT: 4000
        run: npm run dev_node > log.txt 2>&1 &

      - name: Wait for server to start
        run: sleep 10s # Adjust the sleep duration as needed

      - name: Ping server
        run: curl -I localhost:4000

      - name: Run tests
        env:
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
          COOKIE_PASSWORD: ${{ secrets.COOKIE_PASSWORD }}
          DB: ${{ secrets.DB }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
          CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
        run: npm run test

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: server-logs
          path: log.txt
